// Decks — the deck alphabet, card status/completion rules and render-prompt
// composition, re-exported from the server's pure leaf so the client never
// carries a second copy of the roster or the completion math.
export {
  CARD_STATUS,
  DECK_BACK_KEY,
  DECK_CARD_ORIENTATION,
  DECK_CARD_ORIENTATIONS,
  DECK_CARD_ORIENTATION_LABELS,
  DECK_CARD_SIZE,
  DECK_CARD_SIZE_BY_KIND,
  DECK_CARD_SIZE_MAX,
  DECK_CARD_SIZE_MIN,
  DECK_KIND,
  DECK_KINDS,
  DECK_KIND_LABELS,
  DEFAULT_DECK_CARD_ORIENTATION,
  DEFAULT_LAYOUT_PROMPT,
  cardInFlightJobId,
  cardStatus,
  composeCardRenderPrompt,
  defaultDeckCardOrientationPrompt,
  deckCardIdentityPrompt,
  deckCardOrientation,
  deckCardOrientationNegativePrompt,
  deckCardOrientationPrompt,
  deckCardAspectStyle,
  deckCardSize,
  deckCompletion,
} from '../../../server/lib/deckTemplates.js';
