/**
 * `.quality.json` — the numeric quality snapshot a repository carries at its
 * root. The file IS a `buildQualitySnapshot` result verbatim
 * (`{ schemaVersion, repository, measurements }`).
 *
 * PortOS's own checkout is not special: it is a managed app like any other, so
 * its release snapshot is this same file, written by this same publisher, under
 * this same per-app `publishQualitySnapshot` toggle.
 *
 * The filename is deliberately generic and PortOS-agnostic: it is generated
 * data any tool can read, not PortOS configuration. Publishing is opt-in per app
 * (`publishQualitySnapshot`), commits only this one path on a dedicated branch,
 * and lands it through a merge-on-green pull request so the live checkout never
 * diverges from origin and repos that block pushes to the default branch still
 * receive the file.
 */
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { atomicWrite } from '../lib/fileCore.js';

export const APP_QUALITY_SNAPSHOT_FILENAME = '.quality.json';
export const APP_QUALITY_SNAPSHOT_MAX_BYTES = 4 * 1024 * 1024;
export const QUALITY_SNAPSHOT_BRANCH = 'portos/quality-snapshot';

const snapshotPath = repoPath => join(repoPath, APP_QUALITY_SNAPSHOT_FILENAME);
// Byte-identical across every publisher so two files of the same snapshot compare equal.
const serialize = snapshot => `${JSON.stringify(snapshot, null, 2)}\n`;

const QUALITY_PR_TITLE = 'chore: publish quality snapshot';
const QUALITY_PR_BODY = `## Summary
Update the repository \`.quality.json\` numeric quality snapshot generated by PortOS.

## Test plan
- Generated numeric measurements only; no application code changes
- Merge when required CI is green; no code review required
`;

/** Raw bytes, or null when absent/unreadable/oversize. The publish path needs the
 *  exact text so an unchanged snapshot can skip git entirely. */
async function readSnapshotText(repoPath, deps = {}) {
  if (!repoPath) return null;
  const body = await (deps.readFile || readFile)(snapshotPath(repoPath), 'utf8').catch(() => null);
  if (typeof body !== 'string' || Buffer.byteLength(body) > APP_QUALITY_SNAPSHOT_MAX_BYTES) return null;
  return body;
}

/** Parsed `.quality.json`, or null for every failure mode. Never throws. */
export async function readAppQualitySnapshotFile(repoPath, deps = {}) {
  const body = await readSnapshotText(repoPath, deps);
  if (!body) return null;
  // Inline rather than jsonIo.safeJSONParse: routes/apps/crud.js reaches this
  // module statically, so a lib import here lands in the suite import budget.
  const parsed = await Promise.resolve().then(() => JSON.parse(body)).catch(() => null);
  return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : null;
}

function skipped(app, reason) {
  console.log(`📊 Quality snapshot skipped for app ${app?.id}: ${reason}`);
  return { published: false, reason, path: APP_QUALITY_SNAPSHOT_FILENAME };
}

// One tail per checkout. Several audit categories for the same app finish
// together, and read-modify-write against `.quality.json` plus `.git/index` is
// not re-entrant — the second run must see the first run's bytes (and answer
// `no-changes`) rather than race it. Keyed by repo path, not app id: two app
// records can point at one checkout. Same shape as `issueWriteTail`.
const publishTails = new Map();
// Bytes the in-process publisher last landed (or confirmed on origin) for a
// checkout. Origin/default still holds the previous file until the PR merges,
// so the next audit in this process must not open a duplicate PR of the same
// snapshot.
const lastPublishedBody = new Map();

export function __resetQualitySnapshotPublishState() {
  publishTails.clear();
  lastPublishedBody.clear();
}

/**
 * Rebuild the app's numeric snapshot and land it as `.quality.json` through a
 * merge-on-green pull request. An empty snapshot never overwrites a populated
 * file, and an unchanged snapshot never reaches git — an audit that moved
 * nothing leaves no commit.
 */
export async function publishAppQualitySnapshot(app, deps = {}) {
  if (!app?.repoPath) return skipped(app, 'no-repo-path');
  const { repoPath } = app;
  const run = (publishTails.get(repoPath) ?? Promise.resolve())
    .then(() => publishNow(app, deps), () => publishNow(app, deps));
  // The queued value never rejects, so one failed publish cannot poison the tail.
  const queued = run.then(() => {}, () => {});
  publishTails.set(repoPath, queued);
  // Only the newest tail owns the slot; an older one settling must not evict it.
  queued.then(() => { if (publishTails.get(repoPath) === queued) publishTails.delete(repoPath); });
  return run;
}

async function showRefFile(git, repoPath, spec) {
  const result = await git.execGit(['show', spec], repoPath, { ignoreExitCode: true }).catch(() => null);
  if (!result || result.exitCode !== 0) return null;
  const body = result.stdout;
  if (typeof body !== 'string' || Buffer.byteLength(body) > APP_QUALITY_SNAPSHOT_MAX_BYTES) return null;
  return body;
}

function hasOrigin(remote) {
  return Boolean(remote?.origin && (remote.origin.fetch || remote.origin.push || remote.origin['']));
}

async function publishNow(app, deps) {
  const git = deps.git || await import('./git.js');
  if (!await git.isRepo(app.repoPath)) return skipped(app, 'not-a-repo');
  const build = deps.buildQualitySnapshot || (await import('./appQualityFederation.js')).buildQualitySnapshot;
  const snapshot = await build(app, 30, deps);
  if (!snapshot?.measurements?.length) return skipped(app, 'no-evidence');

  const next = serialize(snapshot);
  if (lastPublishedBody.get(app.repoPath) === next) return skipped(app, 'no-changes');

  if (!hasOrigin(await git.getRemote(app.repoPath))) return skipped(app, 'no-remote');

  await git.fetchOrigin(app.repoPath).catch(() => {});
  const defaultBranch = await git.getDefaultBranch(app.repoPath);
  if (!defaultBranch) return skipped(app, 'no-default-branch');

  const fromDefault = await showRefFile(git, app.repoPath, `origin/${defaultBranch}:${APP_QUALITY_SNAPSHOT_FILENAME}`);
  if (fromDefault === next) {
    lastPublishedBody.set(app.repoPath, next);
    return skipped(app, 'no-changes');
  }

  const fromBranch = await showRefFile(git, app.repoPath, `origin/${QUALITY_SNAPSHOT_BRANCH}:${APP_QUALITY_SNAPSHOT_FILENAME}`);
  if (fromBranch === next) {
    const reused = await reuseOpenSnapshotPr(app, git, defaultBranch, deps);
    if (reused.published) lastPublishedBody.set(app.repoPath, next);
    return reused;
  }

  const count = snapshot.measurements.length;
  const result = await landSnapshotPr(app, { body: next, count, defaultBranch, git, deps });
  lastPublishedBody.set(app.repoPath, next);
  return result;
}

async function reuseOpenSnapshotPr(app, git, defaultBranch, deps) {
  const probe = deps.probePrForBranch
    || (await import('./prProbe.js')).probePrForBranch;
  const found = await probe(app.repoPath, QUALITY_SNAPSHOT_BRANCH);
  const prState = typeof found?.prState === 'string' ? found.prState.toUpperCase() : '';
  if (found?.prUrl && found?.prNumber && prState === 'OPEN') {
    const queued = await queueMergeWhenGreen(app, {
      url: found.prUrl, number: found.prNumber, cli: found.cli,
    }, deps);
    console.log(`📊 Quality snapshot PR already open for app ${app.id}: ${found.prUrl}`);
    return {
      published: true, hash: null, path: APP_QUALITY_SNAPSHOT_FILENAME,
      prUrl: found.prUrl, prNumber: found.prNumber, queuedMerge: queued === true,
    };
  }
  return landExistingBranchPr(app, git, defaultBranch, deps);
}

async function landExistingBranchPr(app, git, defaultBranch, deps) {
  const created = await openOrAdoptPr(git, app.repoPath, defaultBranch, deps);
  if (!created?.url) {
    return skipped(app, 'pr-failed');
  }
  const queued = await queueMergeWhenGreen(app, created, deps);
  console.log(`📊 Quality snapshot PR opened for app ${app.id}: ${created.url}`);
  return {
    published: true, hash: null, path: APP_QUALITY_SNAPSHOT_FILENAME,
    prUrl: created.url, prNumber: created.number, queuedMerge: queued === true,
  };
}

async function landSnapshotPr(app, { body, count, defaultBranch, git, deps }) {
  const makeTemp = deps.mkdtemp || mkdtemp;
  const worktreePath = await makeTemp(join(tmpdir(), 'portos-quality-'));
  const addWorktree = deps.addWorktree || (async (args, repo) => {
    const { addWorktreeWithRetry } = await import('./worktreeManager.js');
    return addWorktreeWithRetry(args, repo);
  });
  const removeTemp = deps.rm || rm;

  const run = async () => {
    const baseRef = `origin/${defaultBranch}`;
    await addWorktree(
      // Keep the PR branch free for an in-flight merge/review follow-up. The
      // publisher pushes detached HEAD to the stable remote branch below, so
      // the temporary checkout must not claim that branch locally.
      ['worktree', 'add', '--detach', worktreePath, baseRef],
      app.repoPath,
    );
    await (deps.writeFile || atomicWrite)(join(worktreePath, APP_QUALITY_SNAPSHOT_FILENAME), body);
    await git.stageFiles(worktreePath, [APP_QUALITY_SNAPSHOT_FILENAME]);
    const { hash } = await git.commit(
      worktreePath,
      `chore: publish PortOS quality snapshot (${count} measurements)`,
      { paths: [APP_QUALITY_SNAPSHOT_FILENAME] },
    ).catch(err => git.unstageFiles(worktreePath, [APP_QUALITY_SNAPSHOT_FILENAME])
      .catch(() => {}).then(() => Promise.reject(err)));

    await pushSnapshotBranch(git, app.repoPath, worktreePath);
    const pr = await openOrAdoptPr(git, worktreePath, defaultBranch, deps);
    if (!pr?.url) {
      throw new Error(pr?.error || 'quality snapshot pull request was not created');
    }
    const queued = await queueMergeWhenGreen(app, pr, deps);
    console.log(`📊 Published quality snapshot for app ${app.id}: ${count} measurements → ${hash} (${pr.url})`);
    return {
      published: true, hash, path: APP_QUALITY_SNAPSHOT_FILENAME,
      prUrl: pr.url, prNumber: pr.number, queuedMerge: queued === true,
    };
  };

  return run().finally(() => Promise.all([
    git.execGit(['worktree', 'remove', '--force', worktreePath], app.repoPath, { ignoreExitCode: true })
      .catch(() => {}),
    removeTemp(worktreePath, { recursive: true, force: true }).catch(() => {}),
  ]));
}

async function pushSnapshotBranch(git, repoPath, worktreePath) {
  const remote = await git.execGit(
    ['rev-parse', `origin/${QUALITY_SNAPSHOT_BRANCH}`],
    repoPath,
    { ignoreExitCode: true },
  ).catch(() => null);
  const remoteSha = remote?.exitCode === 0 ? String(remote.stdout || '').trim() : '';
  if (remoteSha && /^[0-9a-f]{7,40}$/i.test(remoteSha)) {
    await git.execGit([
      'push',
      `--force-with-lease=refs/heads/${QUALITY_SNAPSHOT_BRANCH}:${remoteSha}`,
      'origin',
      `HEAD:refs/heads/${QUALITY_SNAPSHOT_BRANCH}`,
    ], worktreePath);
    return;
  }
  await git.execGit(
    ['push', '-u', 'origin', `HEAD:refs/heads/${QUALITY_SNAPSHOT_BRANCH}`],
    worktreePath,
  );
}

async function openOrAdoptPr(git, cwd, base, deps) {
  const created = await git.createPR(cwd, {
    title: QUALITY_PR_TITLE,
    body: QUALITY_PR_BODY,
    base,
    head: QUALITY_SNAPSHOT_BRANCH,
  }).catch(err => ({ success: false, error: err.message }));

  if (created?.success && created.url) return decoratePr(git, created);

  const probe = deps.probePrForBranch
    || (await import('./prProbe.js')).probePrForBranch;
  const found = await probe(cwd, QUALITY_SNAPSHOT_BRANCH);
  const prState = typeof found?.prState === 'string' ? found.prState.toUpperCase() : '';
  if (found?.prUrl && found?.prNumber && prState === 'OPEN') {
    return { url: found.prUrl, number: found.prNumber, cli: found.cli || created?.cli };
  }
  return { error: created?.error || 'pull request was not created' };
}

function decoratePr(git, created) {
  const parsed = git.parsePullRequestUrl(created.url);
  return {
    url: created.url,
    number: parsed?.number ?? null,
    cli: created.cli,
  };
}

async function queueMergeWhenGreen(app, pr, deps) {
  if (!pr?.url || !pr?.number) return false;
  if (pr.cli === 'glab') {
    const execGlab = deps.execGlab || (await import('./gitlab.js')).execGlab;
    const run = args => execGlab(args, app.repoPath, undefined, { rejectOnError: true })
      .then(() => true, err => err);
    let result = await run(['mr', 'merge', String(pr.number), '--yes', '--auto-merge']);
    if (result !== true && /unknown flag|unknown shorthand/i.test(result?.message || '')) {
      result = await run(['mr', 'merge', String(pr.number), '--yes', '--when-pipeline-succeeds']);
    }
    if (result !== true) {
      console.log(`📊 Quality snapshot MR #${pr.number} left open for app ${app.id}: ${result?.message || 'auto-merge unavailable'}`);
      return false;
    }
    return true;
  }
  const queuePendingMerge = deps.queuePendingMerge
    || (await import('./prWatcher.js')).queuePendingMerge;
  return queuePendingMerge(app.id, {
    prUrl: pr.url,
    prNumber: pr.number,
    prBranch: QUALITY_SNAPSHOT_BRANCH,
    sourceAgentId: null,
    sourceTask: {
      id: `quality-snapshot-${app.id}`,
      priority: 'LOW',
      description: 'Publish PortOS quality snapshot',
      metadata: { app: app.id },
    },
  });
}
