/**
 * `.quality.json` — the numeric quality snapshot a repository carries at its
 * root. Writers emit canonical file schema v2 (`appQualitySnapshotFormat.js`).
 * That file is not the peer wire payload: federation stays on
 * `PORTOS_SCHEMA_VERSIONS.appQuality` v1.
 *
 * PortOS's own checkout is not special: it is a managed app like any other, so
 * its release snapshot is this same file, written by this same publisher, under
 * this same per-app `publishQualitySnapshot` toggle.
 *
 * The filename is deliberately generic and PortOS-agnostic: it is generated
 * data any tool can read, not PortOS configuration. Publishing is opt-in per app
 * (`publishQualitySnapshot`), commits only this one path on a dedicated branch,
 * and lands it through a merge-on-green pull request so the live checkout never
 * diverges from origin and repos that block pushes to the default branch still
 * receive the file. Reads never write. A v1 file or historical
 * `quality-snapshot.json` is explicit legacy input.
 */
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { atomicWrite } from '../lib/fileCore.js';
import {
  APP_QUALITY_LEGACY_SNAPSHOT_FILENAME,
  classifyQualitySnapshot,
  qualityFileFromWireSnapshot,
} from './appQualitySnapshotFormat.js';

export const APP_QUALITY_SNAPSHOT_FILENAME = '.quality.json';
export const APP_QUALITY_SNAPSHOT_MAX_BYTES = 4 * 1024 * 1024;
export const QUALITY_SNAPSHOT_BRANCH = 'portos/quality-snapshot';

const snapshotPath = (repoPath, filename = APP_QUALITY_SNAPSHOT_FILENAME) => join(repoPath, filename);
const REWRITE_BLOCKED = new Set(['future', 'unrecognized', 'malformed', 'oversize', 'unreadable']);

const QUALITY_PR_TITLE = 'chore: publish quality snapshot';
const QUALITY_PR_BODY = `## Summary
Update the repository \`.quality.json\` numeric quality snapshot generated by PortOS.

## Test plan
- Generated numeric measurements only; no application code changes
- Merge when required CI is green; no code review required
`;

async function readSnapshotEntry(repoPath, filename, deps = {}) {
  try {
    const body = await (deps.readFile || readFile)(join(repoPath, filename), 'utf8');
    if (typeof body !== 'string') return { status: 'absent' };
    if (Buffer.byteLength(body) > APP_QUALITY_SNAPSHOT_MAX_BYTES) return { status: 'oversize' };
    return { status: 'text', body };
  } catch {
    return { status: 'absent' };
  }
}

/** Parsed `.quality.json`, or null for every failure mode. Never throws.
 *  Legacy filename resolution lives in `readStoredQualitySnapshot`. */
export async function readAppQualitySnapshotFile(repoPath, deps = {}) {
  if (!repoPath) return null;
  const entry = await readSnapshotEntry(repoPath, APP_QUALITY_SNAPSHOT_FILENAME, deps);
  if (entry.status !== 'text') return null;
  // Inline rather than jsonIo.safeJSONParse: routes/apps/crud.js reaches this
  // module statically, so a lib import here lands in the suite import budget.
  const parsed = await Promise.resolve().then(() => JSON.parse(entry.body)).catch(() => null);
  return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : null;
}

async function readClassified(repoPath, filename, deps) {
  if (!repoPath) return { status: 'absent' };
  let body;
  try {
    body = await (deps.readFile || readFile)(snapshotPath(repoPath, filename), 'utf8');
  } catch {
    return { status: 'absent' };
  }
  if (typeof body !== 'string') return { status: 'absent' };
  if (Buffer.byteLength(body) > APP_QUALITY_SNAPSHOT_MAX_BYTES) return { status: 'oversize' };
  return { body, filename, ...classifyQualitySnapshot(body) };
}

/**
 * `.quality.json` when it exists, otherwise the historical `quality-snapshot.json`.
 * A present canonical file is never replaced by the legacy name. Never writes.
 */
export async function readStoredQualitySnapshot(repoPath, deps = {}) {
  const primary = await readClassified(repoPath, APP_QUALITY_SNAPSHOT_FILENAME, deps);
  if (primary.status !== 'absent') return primary;
  const legacy = await readClassified(repoPath, APP_QUALITY_LEGACY_SNAPSHOT_FILENAME, deps);
  return legacy.status === 'absent' ? { status: 'absent', filename: null } : legacy;
}

function skipped(app, reason) {
  console.log(`📊 Quality snapshot skipped for app ${app?.id}: ${reason}`);
  return { published: false, reason, path: APP_QUALITY_SNAPSHOT_FILENAME };
}

// One tail per checkout. Several audit categories for the same app finish
// together, and read-modify-write against `.quality.json` plus `.git/index` is
// not re-entrant — the second run must see the first run's bytes (and answer
// `no-changes`) rather than race it. Keyed by repo path, not app id: two app
// records can point at one checkout. Same shape as `issueWriteTail`.
const publishTails = new Map();
// Bytes the in-process publisher last landed (or confirmed on origin) for a
// checkout. Origin/default still holds the previous file until the PR merges,
// so the next audit in this process must not open a duplicate PR of the same
// snapshot.
const lastPublishedBody = new Map();

export function __resetQualitySnapshotPublishState() {
  publishTails.clear();
  lastPublishedBody.clear();
}

function enqueue(repoPath, task) {
  const run = (publishTails.get(repoPath) ?? Promise.resolve()).then(task, task);
  // The queued value never rejects, so one failed publish cannot poison the tail.
  const queued = run.then(() => {}, () => {});
  publishTails.set(repoPath, queued);
  // Only the newest tail owns the slot; an older one settling must not evict it.
  queued.then(() => { if (publishTails.get(repoPath) === queued) publishTails.delete(repoPath); });
  return run;
}

/**
 * Rebuild the app's numeric snapshot and land it as canonical v2 `.quality.json`
 * through a merge-on-green pull request. An empty snapshot never overwrites a
 * populated file. A v1 file is rewritten when current evidence exists. An
 * already-canonical v2 snapshot with the same records never reaches git.
 */
export async function publishAppQualitySnapshot(app, deps = {}) {
  if (!app?.repoPath) return skipped(app, 'no-repo-path');
  return enqueue(app.repoPath, () => publishNow(app, deps));
}

/**
 * Convert a v1 `.quality.json` or historical `quality-snapshot.json` to canonical
 * v2 using only the rows already in the file. Same isolated worktree and pull
 * request as publication. Does not read the database and does not invent rows.
 */
export async function migrateAppQualitySnapshot(app, deps = {}) {
  if (!app?.repoPath) return skipped(app, 'no-repo-path');
  return enqueue(app.repoPath, () => migrateNow(app, deps));
}

async function readGitSnapshot(git, repoPath, spec) {
  let result;
  try {
    result = await git.execGit(['show', spec], repoPath, {
      ignoreExitCode: true,
      maxBuffer: APP_QUALITY_SNAPSHOT_MAX_BYTES + 1,
    });
  } catch {
    return { status: 'unreadable' };
  }
  if (!result || result.exitCode !== 0) return { status: 'absent' };
  const body = result.stdout;
  if (typeof body !== 'string') return { status: 'absent' };
  if (Buffer.byteLength(body) > APP_QUALITY_SNAPSHOT_MAX_BYTES) return { status: 'oversize' };
  return { body, ...classifyQualitySnapshot(body) };
}

function untouched(app, status) {
  console.log(`📊 Quality snapshot left untouched for app ${app?.id}: ${status}`);
  return { published: false, reason: 'unsupported-format', path: APP_QUALITY_SNAPSHOT_FILENAME };
}

function sameSnapshot(stored, next) {
  if (!stored || stored.status === 'absent' || stored.status === 'unreadable') return false;
  if (stored.body === next) return true;
  return stored.status === 'v2' && stored.canonical === next;
}

async function repoBase(app, git) {
  if (!await git.isRepo(app.repoPath)) return { skip: skipped(app, 'not-a-repo') };
  if (!hasOrigin(await git.getRemote(app.repoPath))) return { skip: skipped(app, 'no-remote') };
  await git.fetchOrigin(app.repoPath).catch(() => {});
  const defaultBranch = await git.getDefaultBranch(app.repoPath);
  if (!defaultBranch) return { skip: skipped(app, 'no-default-branch') };
  return { defaultBranch };
}

function hasOrigin(remote) {
  return Boolean(remote?.origin && (remote.origin.fetch || remote.origin.push || remote.origin['']));
}

async function publishNow(app, deps) {
  const git = deps.git || await import('./git.js');
  // Evidence is resolved before any remote check so a repo that is not a
  // checkout never builds, and an empty projection never reaches git.
  if (!await git.isRepo(app.repoPath)) return skipped(app, 'not-a-repo');
  const build = deps.buildQualitySnapshot || (await import('./appQualityFederation.js')).buildQualitySnapshot;
  const snapshot = await build(app, 30, deps);
  if (!snapshot?.measurements?.length) return skipped(app, 'no-evidence');

  const next = qualityFileFromWireSnapshot(snapshot);
  if (!next) return skipped(app, 'invalid-evidence');
  if (lastPublishedBody.get(app.repoPath) === next) return skipped(app, 'no-changes');

  const base = await repoBase(app, git);
  if (base.skip) return base.skip;
  const onDefault = await readGitSnapshot(
    git, app.repoPath, `origin/${base.defaultBranch}:${APP_QUALITY_SNAPSHOT_FILENAME}`,
  );
  if (REWRITE_BLOCKED.has(onDefault.status)) return untouched(app, onDefault.status);
  // v1 bytes are a real migration even when the scores match. Only v2 that
  // already canonicalizes to `next` is "no changes".
  if (sameSnapshot(onDefault, next)) {
    lastPublishedBody.set(app.repoPath, next);
    return skipped(app, 'no-changes');
  }
  return landOrReuse(app, git, base.defaultBranch, deps, next, snapshot.measurements.length);
}

async function migrateNow(app, deps) {
  const git = deps.git || await import('./git.js');
  if (!await git.isRepo(app.repoPath)) return skipped(app, 'not-a-repo');
  const base = await repoBase(app, git);
  if (base.skip) return base.skip;

  let source = await readGitSnapshot(
    git, app.repoPath, `origin/${base.defaultBranch}:${APP_QUALITY_SNAPSHOT_FILENAME}`,
  );
  let removeLegacy = false;
  if (source.status === 'absent') {
    source = await readGitSnapshot(
      git, app.repoPath, `origin/${base.defaultBranch}:${APP_QUALITY_LEGACY_SNAPSHOT_FILENAME}`,
    );
    removeLegacy = source.status === 'v1' || source.status === 'v2';
  }
  if (source.status === 'absent') return skipped(app, 'no-legacy-file');
  if (REWRITE_BLOCKED.has(source.status)) return untouched(app, source.status);
  if (!source.records?.length || !source.canonical) return skipped(app, 'no-evidence');

  const next = source.canonical;
  if (!removeLegacy && source.status === 'v2' && source.body === next) {
    lastPublishedBody.set(app.repoPath, next);
    return skipped(app, 'no-changes');
  }
  if (lastPublishedBody.get(app.repoPath) === next && !removeLegacy) return skipped(app, 'no-changes');
  return landOrReuse(app, git, base.defaultBranch, deps, next, source.records.length, {
    removeLegacy,
    message: `chore: migrate quality snapshot to schema v2 (${source.records.length} measurements)`,
  });
}

async function landOrReuse(app, git, defaultBranch, deps, next, count, options = {}) {
  const onBranch = await readGitSnapshot(
    git, app.repoPath, `origin/${QUALITY_SNAPSHOT_BRANCH}:${APP_QUALITY_SNAPSHOT_FILENAME}`,
  );
  const legacyOnBranch = options.removeLegacy
    ? await readGitSnapshot(git, app.repoPath, `origin/${QUALITY_SNAPSHOT_BRANCH}:${APP_QUALITY_LEGACY_SNAPSHOT_FILENAME}`)
    : { status: 'absent' };
  // The snapshot branch can hold a future file the default branch does not.
  // Force-pushing canonical v2 over it would discard a format we do not read.
  if (REWRITE_BLOCKED.has(onBranch.status) || REWRITE_BLOCKED.has(legacyOnBranch.status)) {
    return untouched(app, REWRITE_BLOCKED.has(onBranch.status) ? onBranch.status : legacyOnBranch.status);
  }
  if (sameSnapshot(onBranch, next) && legacyOnBranch.status === 'absent') {
    const reused = await reuseOpenSnapshotPr(app, git, defaultBranch, deps);
    if (reused.published) lastPublishedBody.set(app.repoPath, next);
    return reused;
  }
  const result = await landSnapshotPr(app, {
    body: next, count, defaultBranch, git, deps,
    message: options.message, removeLegacy: options.removeLegacy === true,
  });
  lastPublishedBody.set(app.repoPath, next);
  return result;
}

async function reuseOpenSnapshotPr(app, git, defaultBranch, deps) {
  const probe = deps.probePrForBranch
    || (await import('./prProbe.js')).probePrForBranch;
  const found = await probe(app.repoPath, QUALITY_SNAPSHOT_BRANCH);
  const prState = typeof found?.prState === 'string' ? found.prState.toUpperCase() : '';
  if (found?.prUrl && found?.prNumber && prState === 'OPEN') {
    const queued = await queueMergeWhenGreen(app, {
      url: found.prUrl, number: found.prNumber, cli: found.cli,
    }, deps);
    console.log(`📊 Quality snapshot PR already open for app ${app.id}: ${found.prUrl}`);
    return {
      published: true, hash: null, path: APP_QUALITY_SNAPSHOT_FILENAME,
      prUrl: found.prUrl, prNumber: found.prNumber, queuedMerge: queued === true,
    };
  }
  return landExistingBranchPr(app, git, defaultBranch, deps);
}

async function landExistingBranchPr(app, git, defaultBranch, deps) {
  const created = await openOrAdoptPr(git, app.repoPath, defaultBranch, deps);
  if (!created?.url) {
    return skipped(app, 'pr-failed');
  }
  const queued = await queueMergeWhenGreen(app, created, deps);
  console.log(`📊 Quality snapshot PR opened for app ${app.id}: ${created.url}`);
  return {
    published: true, hash: null, path: APP_QUALITY_SNAPSHOT_FILENAME,
    prUrl: created.url, prNumber: created.number, queuedMerge: queued === true,
  };
}

async function landSnapshotPr(app, { body, count, defaultBranch, git, deps, message, removeLegacy = false }) {
  const makeTemp = deps.mkdtemp || mkdtemp;
  const worktreePath = await makeTemp(join(tmpdir(), 'portos-quality-'));
  const addWorktree = deps.addWorktree || (async (args, repo) => {
    const { addWorktreeWithRetry } = await import('./worktreeManager.js');
    return addWorktreeWithRetry(args, repo);
  });
  const removeTemp = deps.rm || rm;
  const commitPaths = removeLegacy
    ? [APP_QUALITY_SNAPSHOT_FILENAME, APP_QUALITY_LEGACY_SNAPSHOT_FILENAME]
    : [APP_QUALITY_SNAPSHOT_FILENAME];
  const commitMessage = message || `chore: publish PortOS quality snapshot (${count} measurements)`;

  const run = async () => {
    const baseRef = `origin/${defaultBranch}`;
    await addWorktree(
      // Keep the PR branch free for an in-flight merge/review follow-up. The
      // publisher pushes detached HEAD to the stable remote branch below, so
      // the temporary checkout must not claim that branch locally.
      ['worktree', 'add', '--detach', worktreePath, baseRef],
      app.repoPath,
    );
    await (deps.writeFile || atomicWrite)(join(worktreePath, APP_QUALITY_SNAPSHOT_FILENAME), body);
    if (removeLegacy) {
      await git.execGit(['rm', '-f', '--', APP_QUALITY_LEGACY_SNAPSHOT_FILENAME], worktreePath);
    }
    await git.stageFiles(worktreePath, [APP_QUALITY_SNAPSHOT_FILENAME]);
    const { hash } = await git.commit(
      worktreePath,
      commitMessage,
      { paths: commitPaths },
    ).catch(err => git.unstageFiles(worktreePath, commitPaths)
      .catch(() => {}).then(() => Promise.reject(err)));

    await pushSnapshotBranch(git, app.repoPath, worktreePath);
    const pr = await openOrAdoptPr(git, worktreePath, defaultBranch, deps);
    if (!pr?.url) {
      throw new Error(pr?.error || 'quality snapshot pull request was not created');
    }
    const queued = await queueMergeWhenGreen(app, pr, deps);
    console.log(`📊 Published quality snapshot for app ${app.id}: ${count} measurements → ${hash} (${pr.url})`);
    return {
      published: true, hash, path: APP_QUALITY_SNAPSHOT_FILENAME,
      prUrl: pr.url, prNumber: pr.number, queuedMerge: queued === true,
    };
  };

  return run().finally(() => Promise.all([
    git.execGit(['worktree', 'remove', '--force', worktreePath], app.repoPath, { ignoreExitCode: true })
      .catch(() => {}),
    removeTemp(worktreePath, { recursive: true, force: true }).catch(() => {}),
  ]));
}

async function pushSnapshotBranch(git, repoPath, worktreePath) {
  const remote = await git.execGit(
    ['rev-parse', `origin/${QUALITY_SNAPSHOT_BRANCH}`],
    repoPath,
    { ignoreExitCode: true },
  ).catch(() => null);
  const remoteSha = remote?.exitCode === 0 ? String(remote.stdout || '').trim() : '';
  if (remoteSha && /^[0-9a-f]{7,40}$/i.test(remoteSha)) {
    await git.execGit([
      'push',
      `--force-with-lease=refs/heads/${QUALITY_SNAPSHOT_BRANCH}:${remoteSha}`,
      'origin',
      `HEAD:refs/heads/${QUALITY_SNAPSHOT_BRANCH}`,
    ], worktreePath);
    return;
  }
  await git.execGit(
    ['push', '-u', 'origin', `HEAD:refs/heads/${QUALITY_SNAPSHOT_BRANCH}`],
    worktreePath,
  );
}

async function openOrAdoptPr(git, cwd, base, deps) {
  const created = await git.createPR(cwd, {
    title: QUALITY_PR_TITLE,
    body: QUALITY_PR_BODY,
    base,
    head: QUALITY_SNAPSHOT_BRANCH,
  }).catch(err => ({ success: false, error: err.message }));

  if (created?.success && created.url) return decoratePr(git, created);

  const probe = deps.probePrForBranch
    || (await import('./prProbe.js')).probePrForBranch;
  const found = await probe(cwd, QUALITY_SNAPSHOT_BRANCH);
  const prState = typeof found?.prState === 'string' ? found.prState.toUpperCase() : '';
  if (found?.prUrl && found?.prNumber && prState === 'OPEN') {
    return { url: found.prUrl, number: found.prNumber, cli: found.cli || created?.cli };
  }
  return { error: created?.error || 'pull request was not created' };
}

function decoratePr(git, created) {
  const parsed = git.parsePullRequestUrl(created.url);
  return {
    url: created.url,
    number: parsed?.number ?? null,
    cli: created.cli,
  };
}

async function queueMergeWhenGreen(app, pr, deps) {
  if (!pr?.url || !pr?.number) return false;
  if (pr.cli === 'glab') {
    const execGlab = deps.execGlab || (await import('./gitlab.js')).execGlab;
    const run = args => execGlab(args, app.repoPath, undefined, { rejectOnError: true })
      .then(() => true, err => err);
    let result = await run(['mr', 'merge', String(pr.number), '--yes', '--auto-merge']);
    if (result !== true && /unknown flag|unknown shorthand/i.test(result?.message || '')) {
      result = await run(['mr', 'merge', String(pr.number), '--yes', '--when-pipeline-succeeds']);
    }
    if (result !== true) {
      console.log(`📊 Quality snapshot MR #${pr.number} left open for app ${app.id}: ${result?.message || 'auto-merge unavailable'}`);
      return false;
    }
    return true;
  }
  const queuePendingMerge = deps.queuePendingMerge
    || (await import('./prWatcher.js')).queuePendingMerge;
  return queuePendingMerge(app.id, {
    prUrl: pr.url,
    prNumber: pr.number,
    prBranch: QUALITY_SNAPSHOT_BRANCH,
    sourceAgentId: null,
    sourceTask: {
      id: `quality-snapshot-${app.id}`,
      priority: 'LOW',
      description: 'Publish PortOS quality snapshot',
      metadata: { app: app.id },
    },
  });
}
