import { join } from 'path';
import { ServerError } from '../lib/errorHandler.js';
import { bufferedSpawnOrThrow } from '../lib/bufferedSpawn.js';
import { commandExists } from '../lib/commandExists.js';
import { atomicWrite, ensureDir, pathExists, PATHS } from '../lib/fileUtils.js';
import { parseGitHubUrl } from '../lib/githubRepoUrl.js';
import { cloneRepo } from './githubCloner.js';
import { createApp, getAllApps, notifyAppsChanged, updateApp } from './apps.js';
import { getAppStatusStrict } from './pm2.js';

export const DEFAULT_EIDOVERSE_WORLDS_REPO = 'https://github.com/anima-research/eidoverse-worlds';
export const EIDOVERSE_VIDEO_REPO = 'https://github.com/anima-research/eidoverse-video';
export const EIDOVERSE_PORT = 8940;
export const EIDOVERSE_PROCESS_NAME = 'eidoverse-worlds';

export function normalizeEidoverseWorldsRepo(worldsRepoUrl) {
  const parsed = parseGitHubUrl(worldsRepoUrl);
  if (!parsed) {
    throw new ServerError('Choose a valid GitHub repository for Eidoverse Worlds.', {
      status: 400,
      code: 'EIDOVERSE_REPO_INVALID',
    });
  }
  return `https://github.com/${parsed.owner}/${parsed.repo}`;
}

export function getEidoversePaths(worldsRepoUrl = DEFAULT_EIDOVERSE_WORLDS_REPO) {
  const normalizedRepoUrl = normalizeEidoverseWorldsRepo(worldsRepoUrl);
  const { owner, repo } = parseGitHubUrl(normalizedRepoUrl);
  const worlds = join(PATHS.repos, owner, repo);
  return Object.freeze({
    worlds,
    video: join(PATHS.repos, 'anima-research', 'eidoverse-video'),
    worldData: join(PATHS.data, 'eidoverse', 'worlds'),
    envFile: join(worlds, '.env.portos'),
  });
}

const INSTALL_TIMEOUT_MS = 10 * 60 * 1000;

const managedAppFields = (paths) => ({
  name: 'Eidoverse Worlds',
  description: 'Private 3D world for a PortOS human and their agents. Installed separately under its own AGPL-3.0 license.',
  repoPath: paths.worlds,
  companionRepoPaths: [paths.video],
  type: 'bun',
  uiPort: EIDOVERSE_PORT,
  apiPort: EIDOVERSE_PORT,
  startCommands: ['bun --env-file=.env.portos server/server.ts'],
  pm2ProcessNames: [EIDOVERSE_PROCESS_NAME],
  envFile: '.env.portos',
  workTracker: 'auto',
  archived: false,
});

const envFileContents = (paths) => [
  '# Generated by PortOS. Machine-local runtime paths; do not commit this file.',
  `PORT=${EIDOVERSE_PORT}`,
  `EIDOVERSE_DIR=${JSON.stringify(paths.video)}`,
  `WORLDS_DIR=${JSON.stringify(paths.worldData)}`,
  '',
].join('\n');

const findManagedApp = (apps, paths) => apps.find((app) => app.repoPath === paths.worlds) || null;

async function registerManagedApp(paths) {
  const apps = await getAllApps();
  const existing = findManagedApp(apps, paths);
  const fields = managedAppFields(paths);
  const app = existing
    ? await updateApp(existing.id, fields)
    : await createApp(fields);
  notifyAppsChanged(existing ? 'update' : 'create', app.id);
  return app;
}

async function installDependencies(directory) {
  await bufferedSpawnOrThrow('bun', ['install', '--frozen-lockfile'], {
    cwd: directory,
    timeoutMs: INSTALL_TIMEOUT_MS,
  });
}

let installInFlight = null;

async function performInstall(worldsRepoUrl) {
  if (!await commandExists('bun')) {
    throw new ServerError('Eidoverse Worlds requires Bun. Install Bun, then retry.', {
      status: 412,
      code: 'EIDOVERSE_BUN_REQUIRED',
    });
  }

  const paths = getEidoversePaths(worldsRepoUrl);
  await Promise.all([
    cloneRepo(worldsRepoUrl),
    cloneRepo(EIDOVERSE_VIDEO_REPO),
  ]);

  await Promise.all([
    installDependencies(paths.worlds),
    installDependencies(join(paths.worlds, 'client')),
  ]);

  await ensureDir(paths.worldData);
  await atomicWrite(paths.envFile, envFileContents(paths));
  await registerManagedApp(paths);

  console.log('🌐 Eidoverse Worlds installed as a managed app');
  return getEidoverseStatus({ worldsRepoUrl });
}

/**
 * Install or resume the optional Eidoverse runtime. The two upstream projects
 * remain independent git checkouts; PortOS writes only an ignored env file and
 * a managed-app record. A process-local promise collapses double-clicks into
 * one clone/install operation.
 */
export async function installEidoverse({ worldsRepoUrl = DEFAULT_EIDOVERSE_WORLDS_REPO } = {}) {
  const normalizedRepoUrl = normalizeEidoverseWorldsRepo(worldsRepoUrl);
  if (installInFlight) return installInFlight;
  installInFlight = performInstall(normalizedRepoUrl).finally(() => {
    installInFlight = null;
  });
  return installInFlight;
}

/**
 * Read setup and runtime state without mutating either external repository.
 * `registryAvailable: false` is kept distinct from a confirmed unregistered
 * app so a damaged apps registry never invites a duplicate installation.
 */
export async function getEidoverseStatus({ worldsRepoUrl = DEFAULT_EIDOVERSE_WORLDS_REPO } = {}) {
  const normalizedRepoUrl = normalizeEidoverseWorldsRepo(worldsRepoUrl);
  const paths = getEidoversePaths(normalizedRepoUrl);
  const [
    bunAvailable,
    worldsRepo,
    videoRepo,
    rootDependencies,
    clientDependencies,
    configured,
    worldDataReady,
    registry,
  ] = await Promise.all([
    commandExists('bun'),
    pathExists(join(paths.worlds, '.git')),
    pathExists(join(paths.video, '.git')),
    pathExists(join(paths.worlds, 'node_modules')),
    pathExists(join(paths.worlds, 'client', 'node_modules')),
    pathExists(paths.envFile),
    pathExists(paths.worldData),
    getAllApps().then(
      (apps) => ({ apps, error: null }),
      (error) => ({ apps: null, error: error.message }),
    ),
  ]);

  const app = registry.apps ? findManagedApp(registry.apps, paths) : null;
  const runtime = app
    ? await getAppStatusStrict(EIDOVERSE_PROCESS_NAME, app.pm2Home).catch(() => null)
    : null;
  const appRegistered = registry.apps === null ? null : Boolean(app);
  const installed = worldsRepo
    && videoRepo
    && rootDependencies
    && clientDependencies
    && configured
    && worldDataReady
    && appRegistered === true;

  return {
    worldsRepoUrl: normalizedRepoUrl,
    installed,
    partial: !installed && [worldsRepo, videoRepo, rootDependencies, clientDependencies, configured, worldDataReady, appRegistered].some(Boolean),
    bunAvailable,
    worldsRepo,
    videoRepo,
    rootDependencies,
    clientDependencies,
    configured,
    worldDataReady,
    registryAvailable: registry.apps !== null,
    registryError: registry.error ? 'Managed-app registry unavailable' : null,
    appRegistered,
    appId: app?.id || null,
    uiPort: EIDOVERSE_PORT,
    runtimeStatus: app
      ? (runtime === null ? 'unknown' : (runtime.status === 'not_found' ? 'not_started' : runtime.status))
      : 'not_registered',
  };
}

export async function assertEidoverseInstalled(options) {
  const status = await getEidoverseStatus(options);
  if (status.installed) return status;
  throw new ServerError('Install Eidoverse Worlds before enabling the feature.', {
    status: 409,
    code: 'EIDOVERSE_NOT_INSTALLED',
  });
}

export const __resetEidoverseInstallForTests = () => {
  installInFlight = null;
};
