import { join } from 'path';
import { ServerError } from '../lib/errorHandler.js';
import { bufferedSpawnOrThrow } from '../lib/bufferedSpawn.js';
import { commandExists } from '../lib/commandExists.js';
import { atomicWrite, ensureDir, pathExists, PATHS } from '../lib/fileUtils.js';
import { cloneRepo } from './githubCloner.js';
import { createApp, getAllApps, notifyAppsChanged, updateApp } from './apps.js';
import { getAppStatusStrict } from './pm2.js';

export const EIDOVERSE_WORLDS_REPO = 'https://github.com/atomantic/eidoverse-worlds';
export const EIDOVERSE_VIDEO_REPO = 'https://github.com/anima-research/eidoverse-video';
export const EIDOVERSE_PORT = 8940;
export const EIDOVERSE_PROCESS_NAME = 'eidoverse-worlds';

export const EIDOVERSE_PATHS = Object.freeze({
  worlds: join(PATHS.repos, 'atomantic', 'eidoverse-worlds'),
  video: join(PATHS.repos, 'anima-research', 'eidoverse-video'),
  worldData: join(PATHS.data, 'eidoverse', 'worlds'),
  envFile: join(PATHS.repos, 'atomantic', 'eidoverse-worlds', '.env.portos'),
});

const INSTALL_TIMEOUT_MS = 10 * 60 * 1000;

const managedAppFields = () => ({
  name: 'Eidoverse Worlds',
  description: 'Private 3D world for a PortOS human and their agents. Installed separately under its own AGPL-3.0 license.',
  repoPath: EIDOVERSE_PATHS.worlds,
  type: 'bun',
  uiPort: EIDOVERSE_PORT,
  apiPort: EIDOVERSE_PORT,
  startCommands: ['bun --env-file=.env.portos server/server.ts'],
  pm2ProcessNames: [EIDOVERSE_PROCESS_NAME],
  envFile: '.env.portos',
  workTracker: 'auto',
  archived: false,
});

const envFileContents = () => [
  '# Generated by PortOS. Machine-local runtime paths; do not commit this file.',
  `PORT=${EIDOVERSE_PORT}`,
  `EIDOVERSE_DIR=${JSON.stringify(EIDOVERSE_PATHS.video)}`,
  `WORLDS_DIR=${JSON.stringify(EIDOVERSE_PATHS.worldData)}`,
  '',
].join('\n');

const findManagedApp = (apps) => apps.find((app) => app.repoPath === EIDOVERSE_PATHS.worlds) || null;

async function registerManagedApp() {
  const apps = await getAllApps();
  const existing = findManagedApp(apps);
  const fields = managedAppFields();
  const app = existing
    ? await updateApp(existing.id, fields)
    : await createApp(fields);
  notifyAppsChanged(existing ? 'update' : 'create', app.id);
  return app;
}

async function installDependencies(directory) {
  await bufferedSpawnOrThrow('bun', ['install', '--frozen-lockfile'], {
    cwd: directory,
    timeoutMs: INSTALL_TIMEOUT_MS,
  });
}

let installInFlight = null;

async function performInstall() {
  if (!await commandExists('bun')) {
    throw new ServerError('Eidoverse Worlds requires Bun. Install Bun, then retry.', {
      status: 412,
      code: 'EIDOVERSE_BUN_REQUIRED',
    });
  }

  await Promise.all([
    cloneRepo(EIDOVERSE_WORLDS_REPO),
    cloneRepo(EIDOVERSE_VIDEO_REPO),
  ]);

  await Promise.all([
    installDependencies(EIDOVERSE_PATHS.worlds),
    installDependencies(join(EIDOVERSE_PATHS.worlds, 'client')),
  ]);

  await ensureDir(EIDOVERSE_PATHS.worldData);
  await atomicWrite(EIDOVERSE_PATHS.envFile, envFileContents());
  await registerManagedApp();

  console.log('🌐 Eidoverse Worlds installed as a managed app');
  return getEidoverseStatus();
}

/**
 * Install or resume the optional Eidoverse runtime. The two upstream projects
 * remain independent git checkouts; PortOS writes only an ignored env file and
 * a managed-app record. A process-local promise collapses double-clicks into
 * one clone/install operation.
 */
export function installEidoverse() {
  if (installInFlight) return installInFlight;
  installInFlight = performInstall().finally(() => {
    installInFlight = null;
  });
  return installInFlight;
}

/**
 * Read setup and runtime state without mutating either external repository.
 * `registryAvailable: false` is kept distinct from a confirmed unregistered
 * app so a damaged apps registry never invites a duplicate installation.
 */
export async function getEidoverseStatus() {
  const [
    bunAvailable,
    worldsRepo,
    videoRepo,
    rootDependencies,
    clientDependencies,
    configured,
    worldDataReady,
    registry,
  ] = await Promise.all([
    commandExists('bun'),
    pathExists(join(EIDOVERSE_PATHS.worlds, '.git')),
    pathExists(join(EIDOVERSE_PATHS.video, '.git')),
    pathExists(join(EIDOVERSE_PATHS.worlds, 'node_modules')),
    pathExists(join(EIDOVERSE_PATHS.worlds, 'client', 'node_modules')),
    pathExists(EIDOVERSE_PATHS.envFile),
    pathExists(EIDOVERSE_PATHS.worldData),
    getAllApps().then(
      (apps) => ({ apps, error: null }),
      (error) => ({ apps: null, error: error.message }),
    ),
  ]);

  const app = registry.apps ? findManagedApp(registry.apps) : null;
  const runtime = app
    ? await getAppStatusStrict(EIDOVERSE_PROCESS_NAME, app.pm2Home).catch(() => null)
    : null;
  const appRegistered = registry.apps === null ? null : Boolean(app);
  const installed = worldsRepo
    && videoRepo
    && rootDependencies
    && clientDependencies
    && configured
    && worldDataReady
    && appRegistered === true;

  return {
    installed,
    partial: !installed && [worldsRepo, videoRepo, rootDependencies, clientDependencies, configured].some(Boolean),
    bunAvailable,
    worldsRepo,
    videoRepo,
    rootDependencies,
    clientDependencies,
    configured,
    worldDataReady,
    registryAvailable: registry.apps !== null,
    registryError: registry.error ? 'Managed-app registry unavailable' : null,
    appRegistered,
    appId: app?.id || null,
    uiPort: EIDOVERSE_PORT,
    runtimeStatus: app
      ? (runtime === null ? 'unknown' : (runtime.status === 'not_found' ? 'not_started' : runtime.status))
      : 'not_registered',
  };
}

export async function assertEidoverseInstalled() {
  const status = await getEidoverseStatus();
  if (status.installed) return status;
  throw new ServerError('Install Eidoverse Worlds before enabling the feature.', {
    status: 409,
    code: 'EIDOVERSE_NOT_INSTALLED',
  });
}

export const __resetEidoverseInstallForTests = () => {
  installInFlight = null;
};
