/**
 * FableLoom record caps — the single source of truth shared by the sanitizer
 * (`records.js`, enforcement) and the route schemas
 * (`server/lib/fableLoomValidation.js`, door check). A leaf module so the lib
 * barrel doesn't transitively load the universe/series service graph.
 */

export const LOOM_LIMITS = Object.freeze({
  NAME_MAX: 200,
  LOGLINE_MAX: 500,
  PREMISE_MAX: 20000,
  STYLE_NOTES_MAX: 4000,
  AUDIENCE_COMMUNICATION_MEDIUM_MAX: 1000,
  STORY_ARC_MAX: 12000,
  PLAN_ITEMS_MAX: 50,
  PLAN_ITEM_TITLE_MAX: 300,
  PLAN_ITEM_DESCRIPTION_MAX: 4000,
  REF_ID_MAX: 64,
  EPISODES_MAX: 100,
  EPISODE_TITLE_MAX: 300,
  SYNOPSIS_MAX: 4000,
  FEEDBACK_MAX: 4000,
  NODES_MAX: 200,
  NODE_TITLE_MAX: 300,
  PROSE_MAX: 20000,
  IMAGE_PROMPT_MAX: 2000,
  VIDEO_PROMPT_MAX: 4000,
  CAMERA_MOVEMENT_MAX: 80,
  VISUAL_BINDINGS_MAX: 12,
  VISUAL_NOTE_MAX: 500,
  VISUAL_PROVENANCE_ASSETS_MAX: 24,
  VISUAL_PROVENANCE_MESSAGES_MAX: 24,
  ENDING_LABEL_MAX: 200,
  TRANSITIONS_MAX: 12,
  INTENT_MAX: 120,
  TRIGGER_MAX: 160,
  TRIGGERS_MAX: 8,
  TRANSITION_DESC_MAX: 500,
  HOLD_LOOPS_MAX: 8,
  AUDIO_INTERVALS_MAX: 50,
  PROVENANCE_CHARACTERS_MAX: 12,
  AMBIENT_DUCK_DB_MIN: -60,
  AMBIENT_DUCK_DB_MAX: 0,
  AMBIENT_DUCK_DB_DEFAULT: -8,
});

