/**
 * OpenAPI 3.1 spec builder for PortOS's public API surface.
 *
 * Native (no swagger-ui dependency): builds the document from the API registry
 * (server/lib/apiRegistry.js) plus per-path operation metadata declared here.
 * Request bodies reuse the same Zod schemas the routes validate against
 * (via `z.toJSONSchema`), so the docs can't drift from validation.
 *
 * Only APIs that are currently `exposed` appear in `paths`. An exposed API
 * with `requireAuth:true` gets a `security` requirement on each of its
 * operations; a passwordless one omits it (anonymous access allowed).
 */

import { z } from 'zod';
import { resolveApiAccess } from './apiRegistry.js';
import { synthesizeBodySchema, txt2imgSchema } from './apiSchemas.js';

const jsonSchema = (schema) => {
  const s = schema ? schema : { type: 'object', properties: {} };
  // OpenAPI 3.1 path objects don't want the top-level $schema dialect marker.
  delete s.$schema;
  return s;
};

const jsonSchemaFromZod = (schema) => {
  return jsonSchema(z.toJSONSchema(schema));
};

// The operation registry is deliberately separate from API_REGISTRY: the
// latter controls exposure, while this table describes the stable contract.
// `x-portos-tool` is an OpenAPI extension and the source for the compact,
// provider-neutral resource generated by buildToolCallingResource().
export const OPENAPI_OPERATIONS = {
  '/api/voice/public/synthesize': {
    post: {
      summary: 'Synthesize speech',
      description: 'Convert text to spoken audio (WAV) using the selected engine and voice.',
      requestBody: {
        required: true, content: { 'application/json': { schema: jsonSchemaFromZod(synthesizeBodySchema) } },
      },
      responses: {
        200: { description: 'WAV audio', content: { 'audio/wav': { schema: { type: 'string', format: 'binary' } } } },
        400: { description: 'Invalid payload or unknown voice' },
      },
      'x-portos-tool': {
        name: 'voice.synthesize', version: 1,
        policy: { privacy: 'personal', sideEffect: 'local-compute', async: false },
      },
    },
  },
  '/api/voice/public/voices': {
    get: {
      summary: 'List voices',
      description: 'Enumerate available voices for an engine (query param `engine`, default = active).',
      parameters: [{ name: 'engine', in: 'query', required: false, schema: { type: 'string', enum: ['kokoro', 'piper'] } }],
      responses: {
        200: {
          description: 'Voice list',
          content: { 'application/json': { schema: {
            type: 'object', required: ['engine', 'voices'],
            properties: { engine: { type: 'string', enum: ['kokoro', 'piper'] }, voices: { type: 'array', items: { type: 'object' } } },
          } } },
        },
      },
      'x-portos-tool': {
        name: 'voice.list-voices', version: 1,
        policy: { privacy: 'internal', sideEffect: 'read', async: false },
      },
    },
  },
  '/api/voice/public/engines': {
    get: {
      summary: 'List engines',
      description: 'Discover available TTS engines and the configured default voice per engine.',
      responses: {
        200: {
          description: 'Engine list + defaults',
          content: { 'application/json': { schema: {
            type: 'object', required: ['engines', 'active', 'defaults'],
            properties: {
              engines: { type: 'array', items: { type: 'string', enum: ['kokoro', 'piper'] } },
              active: { type: 'string', enum: ['kokoro', 'piper'] },
              defaults: { type: 'object', properties: { kokoro: { type: 'string' }, piper: { type: 'string' } } },
            },
          } } },
        },
      },
      'x-portos-tool': {
        name: 'voice.list-engines', version: 1,
        policy: { privacy: 'internal', sideEffect: 'read', async: false },
      },
    },
  },
  '/sdapi/v1/txt2img': {
    post: {
      summary: 'Text-to-image (AUTOMATIC1111-compatible)',
      requestBody: { required: true, content: { 'application/json': { schema: jsonSchemaFromZod(txt2imgSchema) } } },
      responses: {
        200: {
          description: 'Generated image(s)',
          content: { 'application/json': { schema: { $ref: '#/components/schemas/Txt2ImgResponse' } } },
        },
        400: { description: 'Invalid generation parameters' },
      },
      'x-portos-tool': {
        name: 'image.generate', version: 1,
        policy: { privacy: 'personal', sideEffect: 'local-compute', async: true },
      },
    },
  },
  '/sdapi/v1/sd-models': {
    get: {
      summary: 'List image models', responses: { 200: { description: 'Model catalog', content: { 'application/json': { schema: { type: 'array', items: { type: 'object' } } } } } },
      'x-portos-tool': { name: 'image.list-models', version: 1, policy: { privacy: 'internal', sideEffect: 'read', async: false } },
    },
  },
  '/sdapi/v1/samplers': {
    get: {
      summary: 'List samplers', responses: { 200: { description: 'Sampler list', content: { 'application/json': { schema: { type: 'array', items: { type: 'object' } } } } } },
      'x-portos-tool': { name: 'image.list-samplers', version: 1, policy: { privacy: 'internal', sideEffect: 'read', async: false } },
    },
  },
  '/sdapi/v1/options': {
    get: {
      summary: 'Active model/options', responses: { 200: { description: 'Options', content: { 'application/json': { schema: { type: 'object' } } } } },
      'x-portos-tool': { name: 'image.get-options', version: 1, policy: { privacy: 'internal', sideEffect: 'read', async: false } },
    },
  },
  '/sdapi/v1/progress': {
    get: {
      summary: 'Generation progress', responses: { 200: { description: 'Progress', content: { 'application/json': { schema: { type: 'object' } } } } },
      'x-portos-tool': { name: 'image.get-progress', version: 1, policy: { privacy: 'internal', sideEffect: 'read', async: false } },
    },
  },
};

// Attach a `security` requirement to every operation under a path item when the
// API requires auth. Passwordless APIs get an empty array (anonymous allowed).
const applySecurity = (pathItem, requireAuth) => {
  const out = {};
  for (const [method, op] of Object.entries(pathItem)) {
    out[method] = requireAuth ? { ...op, security: [{ bearerAuth: [] }, { basicAuth: [] }] } : { ...op, security: [] };
  }
  return out;
};

const genericPathItem = (path) => ({
  get: { summary: path, responses: { 200: { description: 'OK' } } },
});

const resolveSchema = (schema, spec) => {
  const ref = schema?.$ref;
  if (!ref?.startsWith('#/components/schemas/')) return schema;
  const name = ref.slice('#/components/schemas/'.length);
  return spec?.components?.schemas?.[name] || schema;
};

const operationInputSchema = (operation, spec) => {
  const bodySchema = operation.requestBody?.content?.['application/json']?.schema;
  if (bodySchema) return resolveSchema(bodySchema, spec);

  const parameters = (operation.parameters || []).filter((p) => p.in === 'query' || p.in === 'path');
  if (parameters.length === 0) return { type: 'object', additionalProperties: false, properties: {} };
  return {
    type: 'object',
    additionalProperties: false,
    properties: Object.fromEntries(parameters.map((p) => [p.name, p.schema || {}])),
    ...(parameters.some((p) => p.required) ? { required: parameters.filter((p) => p.required).map((p) => p.name) } : {}),
  };
};

const operationOutputSchema = (operation, spec) => {
  const response = operation.responses?.['200'] || operation.responses?.[200];
  const contents = response?.content || {};
  const mediaType = Object.keys(contents).find((type) => type === 'application/json') || Object.keys(contents)[0];
  return mediaType ? resolveSchema(contents[mediaType].schema || {}, spec) : { type: 'object' };
};

/**
 * Build the OpenAPI 3.1 document for the currently-exposed public APIs.
 * @param {object} settings full settings object (for resolveApiAccess)
 * @param {object} [opts]
 * @param {string} [opts.baseUrl] server base URL (e.g. https://host:5555)
 * @param {string} [opts.version] PortOS version for info.version
 * @returns {object} OpenAPI 3.1 document
 */
export const buildOpenApiSpec = (settings, { baseUrl, version = '0.0.0', includeUnexposed = false } = {}) => {
  const apis = resolveApiAccess(settings);
  const paths = {};
  const tags = [];

  for (const api of apis) {
    if (!api.exposed && !includeUnexposed) continue;
    tags.push({ name: api.id, description: api.description });
    for (const path of api.docPaths) {
      const pathItem = OPENAPI_OPERATIONS[path] || genericPathItem(path);
      // Tag each operation with the API id so docs UIs can group them.
      const tagged = Object.fromEntries(
        Object.entries(pathItem).map(([method, op]) => [method, { tags: [api.id], ...op }]),
      );
      paths[path] = applySecurity(tagged, api.requireAuth);
    }
  }

  return {
    openapi: '3.1.0',
    info: {
      title: 'PortOS Public API',
      version,
      description: includeUnexposed
        ? 'Complete registry contract for externally-callable PortOS services. Runtime exposure is opt-in per API in Settings → API Access.'
        : 'Externally-callable PortOS services. Only APIs you have exposed in Settings → API Access appear here.',
    },
    servers: baseUrl ? [{ url: baseUrl }] : [],
    tags,
    paths,
    components: {
      securitySchemes: {
        bearerAuth: { type: 'http', scheme: 'bearer', description: 'PortOS session token (when the API requires auth).' },
        basicAuth: { type: 'http', scheme: 'basic', description: 'PortOS password via HTTP Basic (username ignored).' },
      },
      schemas: {
        Txt2ImgResponse: {
          type: 'object',
          required: ['images', 'parameters', 'info'],
          properties: {
            images: { type: 'array', items: { type: 'string', contentEncoding: 'base64' } },
            parameters: { type: 'object', additionalProperties: true },
            info: { type: 'string' },
          },
        },
      },
    },
  };
};

/**
 * Project an OpenAPI document into the small canonical resource consumed by
 * tool-calling adapters. Only operations explicitly marked with
 * `x-portos-tool` are eligible; ordinary REST paths never become model tools
 * merely because they are present in the API document.
 *
 * @param {object} spec OpenAPI 3.1 document
 * @returns {object} versioned provider-neutral PortOS tool resource
 */
export const buildToolCallingResource = (spec) => {
  const tools = [];
  const names = new Set();
  for (const [path, pathItem] of Object.entries(spec?.paths || {})) {
    for (const [method, operation] of Object.entries(pathItem)) {
      if (!['get', 'post', 'put', 'patch', 'delete'].includes(method)) continue;
      const metadata = operation['x-portos-tool'];
      if (!metadata) continue;
      if (names.has(metadata.name)) throw new Error(`Duplicate PortOS tool name: ${metadata.name}`);
      names.add(metadata.name);
      tools.push({
        type: 'portos_tool',
        name: metadata.name,
        version: metadata.version,
        description: operation.description || operation.summary || metadata.name,
        input_schema: operationInputSchema(operation, spec),
        output_schema: operationOutputSchema(operation, spec),
        transport: { method: method.toUpperCase(), path },
        policy: {
          ...metadata.policy,
          requiresAuth: (operation.security || []).length > 0,
        },
      });
    }
  }
  tools.sort((a, b) => a.name.localeCompare(b.name));
  return {
    type: 'portos_tool_resource',
    schemaVersion: 1,
    source: { format: 'openapi', version: spec?.openapi || '3.1.0' },
    server: spec?.servers?.[0]?.url || null,
    tools,
  };
};

/** Convert the canonical resource to the OpenAI Responses/Chat tool shape. */
export const toOpenAiTools = (resource) => (resource?.tools || []).map((tool) => ({
  type: 'function',
  function: {
    name: tool.name,
    description: tool.description,
    parameters: tool.input_schema,
  },
}));
